<?php
//Generated by buildORM from the kuis:jawaban


class JawabanBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'jawaban';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function soal()
    {
        return $this->belongsTo('soal', 'soal_id');
    }


    //autogenerated this function...
    public function userjawab()
    {
        return $this->hasMany('UserJawab');
        // return $this->hasOne('UserJawab');
    }


}//the end of class Jawaban
