<?php
//Generated by buildORM from the kuis:kategori


class KategoriBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'kategori';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function lembar()
    {
        return $this->hasMany('Lembar');
        // return $this->hasOne('Lembar');
    }


    //autogenerated this function...
    public function soal()
    {
        return $this->hasMany('Soal');
        // return $this->hasOne('Soal');
    }


}//the end of class Kategori
