<?php
//Generated by buildORM from the kuis:lembar


class LembarBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'lembar';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function user()
    {
        return $this->belongsTo('Cartalyst\\Sentry\\Users\\Eloquent\\User', 'user_id');
    }


    //autogenerated this function...
    public function kategori()
    {
        return $this->belongsTo('kategori', 'kategori_id');
    }


    //autogenerated this function...
    public function soalhaslembar()
    {
        return $this->belongsToMany('Soal', 'soal_has_lembar');
        // return $this->hasOne('SoalHasLembar');
    }


    //autogenerated this function...
    public function userjawab()
    {
        return $this->hasMany('UserJawab');
        // return $this->hasOne('UserJawab');
    }


    //autogenerated this function...
    public function userjawablembar()
    {
        return $this->hasMany('UserJawabLembar');
        // return $this->hasOne('UserJawabLembar');
    }


}//the end of class Lembar
