<?php
//Generated by buildORM from the kuis:migrations


class MigrationBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'migrations';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


}//the end of class Migration
