<?php
//Generated by buildORM from the kuis:soal


class SoalBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'soal';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function kategori()
    {
        return $this->belongsTo('Kategori', 'kategori_id');
    }


    //autogenerated this function...
    public function user()
    {
        return $this->belongsTo('Cartalyst\\Sentry\\Users\\Eloquent\\User', 'user_id');
    }


    //autogenerated this function...
    public function jawaban()
    {
        return $this->hasMany('Jawaban');
        // return $this->hasOne('Jawaban');
    }


    //autogenerated this function...
    public function soalhaslembar()
    {
        return $this->belongsToMany('Lembar', 'soal_has_lembar');
        // return $this->hasOne('SoalHasLembar');
    }


    //autogenerated this function...
    public function userjawab()
    {
        return $this->hasMany('UserJawab');
        // return $this->hasOne('UserJawab');
    }


}//the end of class Soal
