<?php
//Generated by buildORM from the kuis:soal_has_lembar


class SoalHasLembarBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'soal_has_lembar';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function soal()
    {
        return $this->belongsTo('soal', 'soal_id');
    }


    //autogenerated this function...
    public function lembar()
    {
        return $this->belongsTo('lembar', 'lembar_id');
    }


}//the end of class SoalHasLembar
