<?php
//Generated by buildORM from the kuis:user_jawab_lembar


class UserJawabLembarBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'user_jawab_lembar';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function lembar()
    {
        return $this->belongsTo('lembar', 'lembar_id');
    }


    //autogenerated this function...
    public function user()
    {
        return $this->belongsTo('Cartalyst\\Sentry\\Users\\Eloquent\\User', 'user_id');
    }


}//the end of class UserJawabLembar
