<?php
//Generated by buildORM from the kuis:user_jawab


class UserJawabBase extends BaseORM
{ //which extends Eloquent...

    var $table = 'user_jawab';

    protected $guarded = array(); //everything can be added via auto-fill... override this in custom code...


    //autogenerated this function...
    public function soal()
    {
        return $this->belongsTo('soal', 'soal_id');
    }


    //autogenerated this function...
    public function jawaban()
    {
        return $this->belongsTo('jawaban', 'jawaban_id');
    }


    //autogenerated this function...
    public function user_jawab_lembar()
    {
        return $this->belongsTo('lembar', 'user_jawab_lembar_id');
    }


}//the end of class UserJawab
